
-- Clear the existing topic list to ensure a fresh start with the correct data
DELETE FROM public.dsa_topics;

-- Reset the ordering sequence to start from 1 for the new list
ALTER SEQUENCE dsa_topics_order_seq RESTART WITH 1;

-- Insert the complete Striver's SDE Sheet topics from the provided CSV
INSERT INTO public.dsa_topics (category, topic_name, problem_url) VALUES
('Arrays', 'Find the duplicate in an array of N+1 integers.', 'https://leetcode.com/problems/find-the-duplicate-number/'),
('Arrays', 'Sort an array of 0’s 1’s and 2’s', 'https://leetcode.com/problems/sort-colors/'),
('Arrays', 'Repeat and Missing Number', 'https://www.interviewbit.com/problems/repeat-and-missing-number-array/'),
('Arrays', 'Merge two sorted Arrays without extra space', 'https://leetcode.com/problems/merge-sorted-array/'),
('Arrays', 'Kadane''s Algorithm', 'https://leetcode.com/problems/maximum-subarray/'),
('Arrays', 'Merge Overlapping Subintervals', 'https://leetcode.com/problems/merge-intervals/'),
('Arrays Part-II', 'Rotate Matrix', 'https://leetcode.com/problems/rotate-image/'),
('Arrays Part-II', 'Next Permutation', 'https://leetcode.com/problems/next-permutation/'),
('Arrays Part-II', 'Stock buy and Sell', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'),
('Arrays Part-II', 'Inversion of Array (Pre-req: Merge Sort)', 'https://www.codingninjas.com/codestudio/problems/count-inversions_630420'),
('Arrays Part-II', 'Count inversions', 'https://bit.ly/339fFb7'),
('Arrays Part-III', 'Search in a 2D Matrix', 'https://leetcode.com/problems/search-a-2d-matrix/'),
('Arrays Part-III', 'Pow(X,n)', 'https://leetcode.com/problems/powx-n/'),
('Arrays Part-III', 'Majority Element (>N/2 times)', 'https://leetcode.com/problems/majority-element/'),
('Arrays Part-III', 'Majority Element (>N/3 times)', 'https://leetcode.com/problems/majority-element-ii/'),
('Arrays Part-III', 'Grid Unique Paths', 'https://leetcode.com/problems/unique-paths/'),
('Arrays Part-III', 'Reverse Pairs (Leetcode)', 'https://leetcode.com/problems/reverse-pairs/'),
('Arrays Part-IV', '2-Sum-Problem', 'https://leetcode.com/problems/two-sum/'),
('Arrays Part-IV', '4-sum-Problem', 'https://leetcode.com/problems/4sum/'),
('Arrays Part-IV', 'Longest Consecutive Sequence', 'https://leetcode.com/problems/longest-consecutive-sequence/'),
('Arrays Part-IV', 'Largest Subarray with 0 sum', 'https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1'),
('Arrays Part-IV', 'Count number of subarrays with given XOR(this clears a lot of problems)', 'https://www.interviewbit.com/problems/subarray-with-given-xor/'),
('Arrays Part-IV', 'Longest Substring without repeat', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/'),
('Linked List', 'Reverse a LinkedList', 'https://leetcode.com/problems/reverse-linked-list/'),
('Linked List', 'Find the middle of LinkedList', 'https://leetcode.com/problems/middle-of-the-linked-list/'),
('Linked List', 'Merge two sorted Linked List', 'https://leetcode.com/problems/merge-two-sorted-lists/'),
('Linked List', 'Remove N-th node from back of LinkedList', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/'),
('Linked List', 'Add two numbers as LinkedList', 'https://leetcode.com/problems/add-two-numbers/'),
('Linked List', 'Delete a given Node when a node is given. (0(1) solution)', 'https://leetcode.com/problems/delete-node-in-a-linked-list/'),
('Linked List Part-II', 'Find intersection point of Y LinkedList', 'https://leetcode.com/problems/intersection-of-two-linked-lists/'),
('Linked List Part-II', 'Detect a cycle in Linked List', 'https://leetcode.com/problems/linked-list-cycle/'),
('Linked List Part-II', 'Reverse a LinkedList in groups of size k.', 'https://leetcode.com/problems/reverse-nodes-in-k-group/'),
('Linked List Part-II', 'Check if a LinkedList is palindrome or not.', 'https://leetcode.com/problems/palindrome-linked-list/'),
('Linked List Part-II', 'Find the starting point of the Loop of LinkedList', 'https://leetcode.com/problems/linked-list-cycle-ii/'),
('Linked List Part-II', 'Flattening of a LinkedList', 'https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1'),
('Linked List and Arrays', 'Rotate a LinkedList', 'https://leetcode.com/problems/rotate-list/description/'),
('Linked List and Arrays', 'Clone a Linked List with random and next pointer', 'https://leetcode.com/problems/copy-list-with-random-pointer/'),
('Linked List and Arrays', '3 sum', 'https://leetcode.com/problems/3sum/'),
('Linked List and Arrays', 'Trapping rainwater', 'https://leetcode.com/problems/trapping-rain-water/'),
('Linked List and Arrays', 'Remove Duplicate from Sorted array', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/'),
('Linked List and Arrays', 'Max consecutive ones', 'https://leetcode.com/problems/max-consecutive-ones/'),
('Greedy Algorithm', 'N meetings in one room', 'https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1'),
('Greedy Algorithm', 'Minimum number of platforms required for a railway', 'https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1'),
('Greedy Algorithm', 'Job sequencing Problem', 'https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1'),
('Greedy Algorithm', 'Fractional Knapsack Problem', 'https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1'),
('Greedy Algorithm', 'Greedy algorithm to find minimum number of coins', 'https://www.geeksforgeeks.org/find-minimum-number-of-coins-that-make-a-change/'),
('Greedy Algorithm', 'Activity Selection (same as N meeting)', 'https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1'),
('Recursion', 'Subset Sums', 'https://practice.geeksforgeeks.org/problems/subset-sums2234/1'),
('Recursion', 'Subset-II', 'https://leetcode.com/problems/subsets-ii/'),
('Recursion', 'Combination sum-1', 'https://leetcode.com/problems/combination-sum/'),
('Recursion', 'Combination sum-2', 'https://leetcode.com/problems/combination-sum-ii/'),
('Recursion', 'Palindrome Partitioning', 'https://leetcode.com/problems/palindrome-partitioning/'),
('Recursion', 'K-th permutation Sequence', 'https://leetcode.com/problems/permutation-sequence/'),
('Recursion and Backtracking', 'Print all permutations of a string/array', 'https://leetcode.com/problems/permutations/'),
('Recursion and Backtracking', 'N queens Problem', 'https://leetcode.com/problems/n-queens/'),
('Recursion and Backtracking', 'Sudoku Solver', 'https://leetcode.com/problems/sudoku-solver/'),
('Recursion and Backtracking', 'M-coloring Problem', 'https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1'),
('Recursion and Backtracking', 'Rat in a Maze', 'https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1'),
('Recursion and Backtracking', 'Word Break (print all ways)', 'https://bit.ly/3FxgW92'),
('Binary Search', 'The N-th root of an integer', 'https://bit.ly/3rj7HlG'),
('Binary Search', 'Matrix Median', 'https://www.interviewbit.com/problems/matrix-median/'),
('Binary Search', 'Find the single element in a sorted array', 'https://leetcode.com/problems/single-element-in-a-sorted-array/'),
('Binary Search', 'Search element in a sorted and rotated array/ find pivot', 'https://leetcode.com/problems/search-in-rotated-sorted-array/'),
('Binary Search', 'Median of 2 sorted arrays', 'https://leetcode.com/problems/median-of-two-sorted-arrays/'),
('Binary Search', 'K-th element of two sorted arrays', 'https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1'),
('Binary Search', 'Allocate Minimum Number of Pages', 'https://www.interviewbit.com/problems/allocate-books/'),
('Binary Search', 'Aggressive Cows', 'https://www.spoj.com/problems/AGGRCOW/'),
('Heaps', 'Max-Heap, Min-Heap implementation (Only for interviews)', 'https://www.codingninjas.com/codestudio/problems/min-heap_4691801'),
('Heaps', 'Kth Largest Element', 'https://leetcode.com/problems/kth-largest-element-in-an-array/'),
('Heaps', 'Maximum Sum Combination', 'https://www.interviewbit.com/problems/maximum-sum-combinations/'),
('Heaps', 'Find Median from Data Stream', 'https://leetcode.com/problems/find-median-from-data-stream/'),
('Heaps', 'Merge K sorted arrays', 'https://www.codingninjas.com/codestudio/problems/merge-k-sorted-arrays_975379'),
('Heaps', 'K most frequent elements', 'https://leetcode.com/problems/top-k-frequent-elements/'),
('Stack and Queue', 'Implement Stack using Arrays', 'https://bit.ly/3KbHhN4'),
('Stack and Queue', 'Implement Queue using Arrays', 'https://bit.ly/3KbHhN4'),
('Stack and Queue', 'Implement Stack using Queue (using single queue)', 'https://leetcode.com/problems/implement-stack-using-queues/'),
('Stack and Queue', 'Implement Queue using Stack (0(1) amortized method)', 'https://leetcode.com/problems/implement-queue-using-stacks/'),
('Stack and Queue', 'Check for balanced paranthesis', 'https://leetcode.com/problems/valid-parentheses/'),
('Stack and Queue', 'Next Greater Element', 'https://leetcode.com/problems/next-greater-element-i/'),
('Stack and Queue Part-II', 'Next Smaller Element', 'https://www.interviewbit.com/problems/nearest-smaller-element/'),
('Stack and Queue Part-II', 'LRU cache (IMPORTANT)', 'https://leetcode.com/problems/lru-cache/'),
('Stack and Queue Part-II', 'LFU Cache', 'https://leetcode.com/problems/lfu-cache/'),
('Stack and Queue Part-II', 'Largest rectangle in a histogram', 'https://leetcode.com/problems/largest-rectangle-in-histogram/'),
('Stack and Queue Part-II', 'Sliding Window maximum', 'https://leetcode.com/problems/sliding-window-maximum/'),
('Stack and Queue Part-II', 'Implement Min Stack', 'https://leetcode.com/problems/min-stack/'),
('Stack and Queue Part-II', 'Rotten Orange (Using BFS)', 'https://leetcode.com/problems/rotting-oranges/'),
('String', 'Reverse Words in a String', 'https://leetcode.com/problems/reverse-words-in-a-string/'),
('String', 'Longest Palindrome in a string', 'https://leetcode.com/problems/longest-palindromic-substring/'),
('String', 'Roman Number to Integer and vice versa', 'https://leetcode.com/problems/roman-to-integer/'),
('String', 'Implement ATOI/String to Integer', 'https://leetcode.com/problems/string-to-integer-atoi/'),
('String', 'Longest Common Prefix', 'https://leetcode.com/problems/longest-common-prefix/'),
('String', 'Rabin Karp', 'https://leetcode.com/problems/repeated-string-match/solutions/100527/rabin-karp-with-explanation/'),
('String Part-II', 'Z-Function', 'https://www.codingninjas.com/codestudio/problems/z-algorithm_1112619'),
('String Part-II', 'KMP algo / LPS(pi) array', 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/'),
('String Part-II', 'Minimum characters needed to be inserted in the beginning to make it palindromic', 'https://www.interviewbit.com/problems/minimum-characters-required-to-make-a-string-palindromic/'),
('String Part-II', 'Check for Anagrams', 'https://leetcode.com/problems/valid-anagram/'),
('String Part-II', 'Count and Say problem', 'https://leetcode.com/problems/count-and-say/'),
('String Part-II', 'Compare version numbers', 'https://leetcode.com/problems/compare-version-numbers/'),
('Binary Tree', 'Inorder Traversal (with recursion and without recursion)', 'https://leetcode.com/problems/binary-tree-inorder-traversal/'),
('Binary Tree', 'Preorder Traversal (with recursion and without recursion)', 'https://leetcode.com/problems/binary-tree-preorder-traversal/'),
('Binary Tree', 'Postorder Traversal (with recursion and without recursion)', 'https://leetcode.com/problems/binary-tree-postorder-traversal/'),
('Binary Tree', 'LeftView Of Binary Tree', 'https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1'),
('Binary Tree', 'Bottom View of Binary Tree', 'https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1'),
('Binary Tree', 'Top View of Binary Tree', 'https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1'),
('Binary Tree', 'Preorder, Inorder, Postorder in a single traversal', 'https://bit.ly/3r4i1sB'),
('Binary Tree', 'Vertical order traversal', 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/'),
('Binary Tree', 'Root to node path in a Binary Tree', 'https://www.interviewbit.com/problems/path-to-given-node/'),
('Binary Tree', 'Max width of a Binary Tree', 'https://leetcode.com/problems/maximum-width-of-binary-tree/'),
('Binary Tree Part-II', 'Level order Traversal / Level order traversal in spiral form', 'https://leetcode.com/problems/binary-tree-level-order-traversal/'),
('Binary Tree Part-II', 'Height of a Binary Tree', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/'),
('Binary Tree Part-II', 'Diameter of a Binary Tree', 'https://leetcode.com/problems/diameter-of-binary-tree/'),
('Binary Tree Part-II', 'Check if the Binary tree is height-balanced or not', 'https://leetcode.com/problems/balanced-binary-tree/'),
('Binary Tree Part-II', 'LCA in Binary Tree', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/'),
('Binary Tree Part-II', 'Check if two trees are identical or not', 'https://leetcode.com/problems/same-tree/'),
('Binary Tree Part-II', 'Zig-Zag traversal of a Binary Tree', 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/'),
('Binary Tree Part-II', 'Boundary Traversal of a Binary Tree', 'https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1'),
('Binary Tree part-III', 'Maximum path sum', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/'),
('Binary Tree part-III', 'Construct Binary Tree from inorder and preorder', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/'),
('Binary Tree part-III', 'Construct Binary Tree from Inorder and Postorder', 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/'),
('Binary Tree part-III', 'Symmetric Binary Tree', 'https://leetcode.com/problems/symmetric-tree/'),
('Binary Tree part-III', 'Flatten Binary Tree to LinkedList', 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/'),
('Binary Tree part-III', 'Check if a Binary Tree is mirror of itself or not', 'https://practice.geeksforgeeks.org/problems/symmetric-tree/1'),
('Binary Tree part-III', 'Check for Children Sum Property', 'https://bit.ly/33yExMM'),
('Binary Search Trees', 'Populate Next Right pointers of Tree', 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/'),
('Binary Search Trees', 'Search in a BST', 'https://leetcode.com/problems/search-in-a-binary-search-tree/'),
('Binary Search Trees', 'Construct BST from given keys', 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/'),
('Binary Search Trees', 'Construct BST from preorder traversal', 'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/'),
('Binary Search Trees', 'Check if a BT is BST or not', 'https://leetcode.com/problems/validate-binary-search-tree/'),
('Binary Search Trees', 'Find LCA of two nodes in BST', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/'),
('Binary Search Trees', 'Find the inorder successor/predecessor of a given Key in BST', 'https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1'),
('Binary Search Trees Part-II', 'Floor in a BST', 'https://www.codingninjas.com/codestudio/problems/floor-from-bst_920457'),
('Binary Search Trees Part-II', 'Ceil in a BST', 'https://www.codingninjas.com/codestudio/problems/ceil-from-bst_920464'),
('Binary Search Trees Part-II', 'Find K-th smallest element in BST', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/'),
('Binary Search Trees Part-II', 'Find K-th largest element in BST', 'https://practice.geeksforgeeks.org/problems/kth-largest-element-in-bst/1'),
('Binary Search Trees Part-II', 'Find a pair with a given sum in BST', 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/'),
('Binary Search Trees Part-II', 'BST iterator', 'https://leetcode.com/problems/binary-search-tree-iterator/'),
('Binary Search Trees Part-II', 'Size of the largest BST in a Binary Tree', 'https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/'),
('Binary Search Trees Part-II', 'Serialize and deserialize a Binary Tree', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/'),
('BST', 'Find a pair with a given sum in BST', 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/'),
('BST', 'Recover BST', 'https://leetcode.com/problems/recover-binary-search-tree/'),
('BST', 'Largest BST in a BT', 'https://leetcode.com/problems/largest-bst-subtree/'),
('Trie', 'Implement Trie (Prefix Tree)', 'https://leetcode.com/problems/implement-trie-prefix-tree/'),
('Trie', 'Implement Trie – 2 (Prefix Tree)', 'https://bit.ly/3qqSoiF'),
('Trie', 'Longest String with All Prefixes', 'https://bit.ly/3qrS6tF'),
('Trie', 'Number of Distinct Substrings in a String', 'https://bit.ly/3qtnJ3Y'),
('Trie', 'Power Set', 'https://practice.geeksforgeeks.org/problems/power-set1829/1'),
('Trie', 'Maximum XOR of two numbers in an array', 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/'),
('Trie', 'Maximum XOR With an Element From Array', 'https://leetcode.com/problems/maximum-xor-with-an-element-from-array/'),
('Graph', 'Clone a graph', 'https://leetcode.com/problems/clone-graph/'),
('Graph', 'DFS', 'https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1'),
('Graph', 'BFS', 'https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1'),
('Graph', 'Detect A cycle in Undirected Graph using BFS', 'https://leetcode.com/problems/course-schedule-ii/'),
('Graph', 'Detect A cycle in Undirected Graph using DFS', 'https://leetcode.com/problems/course-schedule-ii/'),
('Graph', 'Detect A cycle in a Directed Graph using DFS', 'https://leetcode.com/problems/course-schedule/'),
('Graph', 'Detect A cycle in a Directed Graph using BFS', 'https://leetcode.com/problems/course-schedule/'),
('Graph', 'Topological sort BFS', 'https://practice.geeksforgeeks.org/problems/topological-sort/1'),
('Graph', 'Topological sort DFS', 'https://practice.geeksforgeeks.org/problems/topological-sort/1'),
('Graph', 'Number of islands(Do in Grid and Graph both)', 'https://leetcode.com/problems/number-of-islands/'),
('Graph', 'Bipartite Check using BFS', 'https://leetcode.com/problems/is-graph-bipartite/'),
('Graph', 'Bipartite Check using DFS', 'https://leetcode.com/problems/is-graph-bipartite/'),
('Graph Part-II', 'Strongly Connected Component(using KosaRaju’s algo)', 'https://practice.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1'),
('Graph Part-II', 'Dijkstra’s Algorithm', 'https://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1'),
('Graph Part-II', 'Bellman-Ford Algo', 'https://practice.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/0/?category%5B%5D=Graph&query=category%5B%5DGraph'),
('Graph Part-II', 'Floyd Warshall Algo', 'https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1'),
('Graph Part-II', 'MST(Prims Algo)', 'https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1'),
('Graph Part-II', 'MST(Kruskal’s Algo)', 'https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1'),
('DP', 'Max Product Subarray', 'https://leetcode.com/problems/maximum-product-subarray/'),
('DP', 'Longest Increasing Subsequence', 'https://leetcode.com/problems/longest-increasing-subsequence/'),
('DP', 'Longest Common Subsequence', 'https://leetcode.com/problems/longest-common-subsequence/'),
('DP', '0-1 Knapsack', 'https://leetcode.com/problems/ones-and-zeroes/'),
('DP', 'Edit Distance', 'https://leetcode.com/problems/edit-distance/'),
('DP', 'Maximum sum increasing subsequence', 'https://practice.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4749/1'),
('DP', 'Matrix Chain Multiplication', 'https://www.interviewbit.com/problems/matrix-chain-multiplication/'),
('DP Part-II', 'Minimum sum path in the matrix, (count paths and similar type do, also backtrack to find the path)', 'https://leetcode.com/problems/minimum-path-sum/'),
('DP Part-II', 'Coin change', 'https://leetcode.com/problems/coin-change/'),
('DP Part-II', 'Subset Sum', 'https://leetcode.com/problems/partition-equal-subset-sum/'),
('DP Part-II', 'Rod Cutting', 'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/'),
('DP Part-II', 'Egg Dropping', 'https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle-1587115620/1'),
('DP Part-II', 'Word Break', 'https://leetcode.com/problems/word-break/'),
('DP Part-II', 'Palindrome Partitioning (MCM Variation)', 'https://leetcode.com/problems/palindrome-partitioning-ii/'),
('DP Part-II', 'Job Sequencing', 'https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1');
