
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoktxkflnllfvonneiws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFva3R4a2ZsbmxsZnZvbm5laXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTk3NTgsImV4cCI6MjA2NTQ3NTc1OH0.M8ahNSdUUv3_rCqu8POidcC7dOQy0b89iKWRuyFEdVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
